### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by Gor027** [scylladb/cpp-rs-driver#105]
The ScyllaDB Rust driver will soon be enhanced with support for serverless https://github.com/scylladb/scylla-rust-driver/pull/614. The C++ bindings should also support serverless and this will imply to:
* remove existing DBaaS-related functions from API
* add appropriate API functions for serverless support
* modify `DbaasTests` tests to properly test serverless support

It is also necessary to add code examples in https://github.com/scylladb/serverless-examples.

**Comment by mykaul** [comment]
This is not needed, closing.

**Comment by tzach** [comment]
Tablets is the new Serverless
