### ISSUE TITLE
Implement RackAwarePolicy loadbalancing policy

### ISSUE THREAD

**Issue by dkropachev** [scylladb/cpp-rs-driver#156]
We need to implement an API that matches `RackAwarePolicy` of `cpp-driver` that was implemented at https://github.com/scylladb/cpp-driver/pull/73

**Comment by roydahan** [comment]
Do we have it as part of the list for CPP-rust parity with original cpp driver?
(I couldn't find it by its name)

**Comment by wprzytula** [comment]
> Do we have it as part of the list for CPP-rust parity with original cpp driver? (I couldn't find it by its name)

No; apparently, the list does not contain our cpp-driver's API extensions, because it predates them.

**Comment by roydahan** [comment]
> > Do we have it as part of the list for CPP-rust parity with original cpp driver? (I couldn't find it by its name)
> 
> No; apparently, the list does not contain our cpp-driver's API extensions, because it predates them.

@muzarski can you please add it to the spreadsheet we track the cpp-rust missing functionalities.

**Comment by muzarski** [comment]
> > > Do we have it as part of the list for CPP-rust parity with original cpp driver? (I couldn't find it by its name)
> > 
> > 
> > No; apparently, the list does not contain our cpp-driver's API extensions, because it predates them.
> 
> @muzarski can you please add it to the spreadsheet we track the cpp-rust missing functionalities.

Done, added entries for `cass_cluster_set_load_balance_rack_aware[_n]` missing API functions
