### ISSUE TITLE
CassSsl

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#34]
Should be fairly straightforward, as both drivers are using OpenSSL

Functions to implement:

- [x] `cass_ssl_new_no_lib_init`
- [x] `cass_ssl_free`
- [x] `cass_ssl_add_trusted_cert`
- [x] `cass_ssl_add_trusted_cert_n`
- [x] `cass_ssl_set_verify_flags`
- [x] `cass_ssl_set_cert`
- [x] `cass_ssl_set_cert_n`
- [x] `cass_ssl_set_private_key`
- [x] `cass_ssl_set_private_key_n`
- [x] `cass_cluster_set_ssl`

Docs for cpp driver:
https://docs.datastax.com/en/developer/cpp-driver/2.16/api/struct.CassSsl/

Docs for rust driver: 
https://cvybhu.github.io/scyllabook/connecting/tls.html

Rust usage example:
https://github.com/scylladb/scylla-rust-driver/blob/main/examples/tls.rs

**Comment by Gor027** [comment]
Closing this issue, as SSL support is already merged with [this PR](https://github.com/scylladb/cpp-rust-driver/pull/70).
