### ISSUE TITLE
CassResult missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#35]
Both _count and cass_result_column_type and  cass_result_column_name should be easy (if Rust driver has support, but it probably has).
Not sure about cass_result_column_data_type and cass_result_paging_state_token.

- [x] `cass_result_row_count`
- [x] `cass_result_column_count`
- [x] `cass_result_column_name`
- [ ] `cass_result_column_type`
- [ ] `cass_result_column_data_type`
- [x] `cass_result_first_row`
- [x] `cass_result_paging_state_token`

API docs:
https://docs.datastax.com/en/developer/cpp-driver/2.16/api/struct.CassResult/

**Comment by Lorak-mmk** [comment]
`cass_result_column_type` and `cass_result_column_data_type` require https://github.com/hackathon-rust-cpp/cpp-rust-driver/pull/18/

**Comment by muzarski** [comment]
This will be closed when https://github.com/scylladb/cpp-rust-driver/pull/136 is merged.
