### ISSUE TITLE
CassCluster missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#36]
Most of them probably need to be implemented in Rust driver first. we need to evaluate which one are possible to implement (and which ones even make sense to think about), and which ones need support in Rust driver.
Complete list:

- [ ] `cass_cluster_set_local_address`
- [ ] `cass_cluster_set_local_address_n`
- [ ] `cass_cluster_set_local_port_range`
- [x] `cass_cluster_set_use_beta_protocol_version`
- [x] `cass_cluster_set_consistency`
- [x] `cass_cluster_set_serial_consistency`
- [ ] `cass_cluster_set_num_threads_io`
- [ ] `cass_cluster_set_queue_size_io`
- [ ] `cass_cluster_set_core_connections_per_host`
- [ ] `cass_cluster_set_max_connections_per_host`
- [ ] `cass_cluster_set_reconnect_wait_time`
- [ ] `cass_cluster_set_constant_reconnect`
- [ ] `cass_cluster_set_exponential_reconnect`
- [ ] `cass_cluster_set_coalesce_delay`
- [ ] `cass_cluster_set_new_request_ratio`
- [ ] `cass_cluster_set_max_concurrent_creation`
- [ ] `cass_cluster_set_max_concurrent_requests_threshold`
- [ ] `cass_cluster_set_max_requests_per_flush`
- [ ] `cass_cluster_set_write_bytes_high_water_mark`
- [ ] `cass_cluster_set_write_bytes_low_water_mark`
- [ ] `cass_cluster_set_pending_requests_high_water_mark`
- [ ] `cass_cluster_set_pending_requests_low_water_mark`
- [ ] `cass_cluster_set_request_timeout`
- [ ] `cass_cluster_set_resolve_timeout`
- [ ] `cass_cluster_set_max_schema_wait_time`
- [ ] `cass_cluster_set_tracing_max_wait_time`
- [ ] `cass_cluster_set_tracing_retry_wait_time`
- [ ] `cass_cluster_set_tracing_consistency`
- [ ] `cass_cluster_set_token_aware_routing_shuffle_replicas`
- [x] `cass_cluster_set_latency_aware_routing`
- [x] `cass_cluster_set_latency_aware_routing_settings`
- [ ] `cass_cluster_set_whitelist_filtering`
- [ ] `cass_cluster_set_whitelist_filtering_n`
- [ ] `cass_cluster_set_blacklist_filtering`
- [ ] `cass_cluster_set_blacklist_filtering_n`
- [ ] `cass_cluster_set_whitelist_dc_filtering`
- [ ] `cass_cluster_set_whitelist_dc_filtering_n`
- [ ] `cass_cluster_set_blacklist_dc_filtering`
- [ ] `cass_cluster_set_blacklist_dc_filtering_n`
- [ ] `cass_cluster_set_tcp_keepalive`
- [ ] `cass_cluster_set_connection_heartbeat_interval`
- [ ] `cass_cluster_set_connection_idle_timeout`
- [x] `cass_cluster_set_use_schema`
- [ ] `cass_cluster_set_use_hostname_resolution`
- [ ] `cass_cluster_set_use_randomized_contact_points`
- [ ] `cass_cluster_set_max_reusable_write_objects`
- [ ] `cass_cluster_set_prepare_on_all_hosts`
- [ ] `cass_cluster_set_prepare_on_up_or_add_host`
- [ ] `cass_cluster_set_no_compact`
- [ ] `cass_cluster_set_host_listener_callback`
- [ ] `cass_cluster_set_application_name`
- [ ] `cass_cluster_set_application_name_n`
- [ ] `cass_cluster_set_application_version`
- [ ] `cass_cluster_set_application_version_n`
- [ ] `cass_cluster_set_client_id`
- [ ] `cass_cluster_set_monitor_reporting_interval`

**Comment by roydahan** [comment]
Closing this one and we will have a ticket per topic according to our plan of missing implementations.
