### ISSUE TITLE
CassRetryPolicy

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#37]
That is important functionality that we need to have.

I don't know if Rust drivers supports it - we need to check, and implement it there if it doesn't,

Functions:

- [x] `cass_retry_policy_default_new`
- [x] `cass_retry_policy_downgrading_consistency_new`
- [x] `cass_retry_policy_fallthrough_new`
- [ ] `cass_retry_policy_logging_new`
- [x] `cass_retry_policy_free`
- [x] `cass_cluster_set_retry_policy`
- [x] `cass_statement_set_retry_policy`
- [x] `cass_batch_set_retry_policy`
- [x] `cass_execution_profile_set_retry_policy`

**Comment by roydahan** [comment]
The missing one is in the plan.
We will have a separate ticket for it.
