### ISSUE TITLE
CassExecProfile

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#38]
Useful feature of cppdriver that lets user create predefined set of options that can be then used with queries.

Rust driver doesn't support them - we need to decide if we want to implement it there, or fully in our wrapper.
I'd be leaning towards implementation in the driver - the feature is useful in cppdriver, and could be useful in Rust driver, and could bring performance benefits.

Functions:

- [x] `cass_execution_profile_new`
- [x] `cass_execution_profile_free`
- [x] `cass_execution_profile_set_request_timeout`
- [x] `cass_execution_profile_set_consistency`
- [x] `cass_execution_profile_set_serial_consistency`
- [x] `cass_execution_profile_set_load_balance_round_robin`
- [x] `cass_execution_profile_set_load_balance_dc_aware`
- [x] `cass_execution_profile_set_load_balance_dc_aware_n`
- [x] `cass_execution_profile_set_token_aware_routing`
- [ ] `cass_execution_profile_set_token_aware_routing_shuffle_replicas`
- [x] `cass_execution_profile_set_latency_aware_routing`
- [x] `cass_execution_profile_set_latency_aware_routing_settings`
- [ ] `cass_execution_profile_set_whitelist_filtering`
- [ ] `cass_execution_profile_set_whitelist_filtering_n`
- [ ] `cass_execution_profile_set_blacklist_filtering`
- [ ] `cass_execution_profile_set_blacklist_filtering_n`
- [ ] `cass_execution_profile_set_whitelist_dc_filtering`
- [ ] `cass_execution_profile_set_whitelist_dc_filtering_n`
- [ ] `cass_execution_profile_set_blacklist_dc_filtering`
- [ ] `cass_execution_profile_set_blacklist_dc_filtering_n`
- [x] `cass_execution_profile_set_retry_policy`
- [x] `cass_execution_profile_set_constant_speculative_execution_policy`
- [ ] `cass_execution_profile_set_no_speculative_execution_policy`
- [x] `cass_batch_set_execution_profile`
- [x] `cass_batch_set_execution_profile_n`
- [x] `cass_statement_set_execution_profile`
- [x] `cass_statement_set_execution_profile_n`
- [x] `cass_cluster_set_execution_profile`
- [x] `cass_cluster_set_execution_profile_n`

**Comment by Gor027** [comment]
This will be fixed when #107 is merged. Functions that will be left unimplemented should be added to the README under the limitations section.

**Comment by Lorak-mmk** [comment]
First we need to add unsupported functions to README

**Comment by Gor027** [comment]
I have updated the list of the unimplemented functions. The Rust driver does not support blacklist/whitelist filtering, and as I understand shuffling replicas is always enabled. The `cass_cluster_set_no_speculative_execution_policy` function is implemented so I guess `cass_execution_profile_set_no_speculative_execution_policy` can be implemented similarly.

**Comment by roydahan** [comment]
All the missing ones are part of the plan.
We will have a new ticket per topic.
