### ISSUE TITLE
CassSession missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#39]
Some functions are still missing

- [x] `cass_session_connect_keyspace`
- [x] `cass_session_connect_keyspace_n`
- [x] `cass_session_close`
- [x] `cass_session_prepare_from_existing`
- [ ] `cass_session_get_metrics`
- [ ] `cass_session_get_speculative_execution_metrics`
- [ ] `cass_session_get_client_id`

First 3 are the most important (and probably are supported by rust driver). 
prepare_from_existing might be problematic - Rust driver doesn't support it (and I think they are right to, it's a stupid API imho), so we should think if this can be implemented in the wrapper.
Last one - easy if Rust supports.
metrics - I don't think Rust supports it (but it's great if they do), what should we do about them?

**Comment by roydahan** [comment]
The missing ones are part of the plan.
Closing in favor of dedicated issues.
