### ISSUE TITLE
Meta information

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#40]
Too many functions to list here - all are in the document, marked red.
Rust driver doesn't support it, so it need to be implemented there.

**Comment by Gor027** [comment]
Fetching schema metadata information is partially available in the Rust driver and there are open PRs that add support for fetching metadata about keyspaces, UDTs, materialized views, tables and columns.
Schema metadata and UDTs: https://github.com/scylladb/cpp-rust-driver/pull/72
Materialized views, tables and columns: https://github.com/scylladb/cpp-rust-driver/pull/76

**Comment by roydahan** [comment]
Closing this one, we have it in the document per topic.
