### ISSUE TITLE
CassStatement missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#43]
Function list:

- [ ] `cass_statement_reset_parameters`
- [ ] `cass_statement_add_key_index`
- [ ] `cass_statement_set_keyspace`
- [ ] `cass_statement_set_keyspace_n`
- [x] `cass_statement_set_consistency`
- [x] `cass_statement_set_serial_consistency`
- [x] `cass_statement_set_paging_state_token`
- [x] `cass_statement_set_timestamp`
- [x] `cass_statement_set_request_timeout`
- [ ] `cass_statement_set_host`
- [ ] `cass_statement_set_host_n`
- [ ] `cass_statement_set_host_inet`
- [ ] `cass_statement_set_node`

First one should be easy, rest depends on rust support - I expect at least some are present and can be implemented.

**Comment by roydahan** [comment]
Closing this one, we will open a new one per topic.
