### ISSUE TITLE
Misc functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#45]
This is the issue for all functions that that fit anywhere else.

List:

- [ ] `cass_consistency_string`
- [ ] `cass_write_type_string`
- [x] `cass_error_desc`
- [x] `cass_log_cleanup`
- [x] `cass_log_set_level`
- [x] `cass_log_set_callback`
- [x] `cass_log_get_callback_and_data`
- [x] `cass_log_set_queue_size`
- [x] `cass_log_level_string`
- [ ] `cass_alloc_set_functions`

First 3 and cass_log_level_string should be really easy.
I don't think the rest can be implemented in any meaningful way without a lot of work - we should probably skip them for now.

**Comment by Gor027** [comment]
Support for logging will be added in [this PR](https://github.com/scylladb/cpp-rust-driver/pull/78).

**Comment by roydahan** [comment]
The missing ones are part of the document plan, will have their own issue.
