### ISSUE TITLE
CassTuple

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#48]
Function list:

- [x] `cass_tuple_new`
- [x] `cass_tuple_new_from_data_type`
- [x] `cass_tuple_free`
- [x] `cass_tuple_data_type`
- [x] `cass_tuple_set_null`
- [x] `cass_tuple_set_int8`
- [x] `cass_tuple_set_int16`
- [x] `cass_tuple_set_int32`
- [x] `cass_tuple_set_uint32`
- [x] `cass_tuple_set_int64`
- [x] `cass_tuple_set_float`
- [x] `cass_tuple_set_double`
- [x] `cass_tuple_set_bool`
- [x] `cass_tuple_set_string`
- [x] `cass_tuple_set_string_n`
- [x] `cass_tuple_set_bytes`
- [ ] `cass_tuple_set_custom`
- [ ] `cass_tuple_set_custom_n`
- [x] `cass_tuple_set_uuid`
- [x] `cass_tuple_set_inet`
- [x] `cass_tuple_set_decimal`
- [x] `cass_tuple_set_duration`
- [x] `cass_tuple_set_collection`
- [x] `cass_tuple_set_tuple`
- [x] `cass_tuple_set_user_type`
- [x] `cass_statement_bind_tuple`
- [x] `cass_statement_bind_tuple_by_name`
- [x] `cass_statement_bind_tuple_by_name_n`

**Comment by muzarski** [comment]
We are not planning to support custom types. Closing this one, since remaining API functions are implemented.
