### ISSUE TITLE
CassDataType missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#49]
Function list:

- [x] `cass_data_type_new_tuple`
- [ ] `cass_data_type_is_frozen`
- [x] `cass_data_type_type_name`
- [x] `cass_data_type_keyspace`
- [x] `cass_data_type_class_name`
- [x] `cass_data_type_set_class_name`
- [x] `cass_data_type_set_class_name_n`
- [x] `cass_data_type_sub_data_type`
- [x] `cass_data_type_sub_data_type_by_name`
- [x] `cass_data_type_sub_data_type_by_name_n`
- [x] `cass_data_type_sub_type_name`
- [x] `cass_data_type_add_sub_type`
- [x] `cass_data_type_add_sub_value_type`

**Comment by Gor027** [comment]
`cass_data_type_is_frozen` implementation will be added in [this PR](https://github.com/scylladb/cpp-rust-driver/pull/77).
