### ISSUE TITLE
CassUserType missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#51]
Function list:

- [x] `cass_user_type_data_type`
- [x] `cass_user_type_set_null`
- [x] `cass_user_type_set_int8`
- [x] `cass_user_type_set_int16`
- [x] `cass_user_type_set_int32`
- [x] `cass_user_type_set_uint32`
- [x] `cass_user_type_set_int64`
- [x] `cass_user_type_set_float`
- [x] `cass_user_type_set_double`
- [x] `cass_user_type_set_bool`
- [x] `cass_user_type_set_string`
- [x] `cass_user_type_set_string_n`
- [x] `cass_user_type_set_bytes`
- [ ] `cass_user_type_set_custom`
- [ ] `cass_user_type_set_custom_n`
- [ ] `cass_user_type_set_custom_by_name`
- [ ] `cass_user_type_set_custom_by_name_n`
- [x] `cass_user_type_set_uuid`
- [x] `cass_user_type_set_uuid_by_name`
- [x] `cass_user_type_set_uuid_by_name_n`
- [x] `cass_user_type_set_inet`
- [x] `cass_user_type_set_inet_by_name`
- [x] `cass_user_type_set_inet_by_name_n`
- [x] `cass_user_type_set_decimal`
- [x] `cass_user_type_set_decimal_by_name`
- [x] `cass_user_type_set_decimal_by_name_n`
- [x] `cass_user_type_set_duration`
- [x] `cass_user_type_set_duration_by_name`
- [x] `cass_user_type_set_duration_by_name_n`
- [x] `cass_user_type_set_collection`
- [x] `cass_user_type_set_collection_by_name`
- [x] `cass_user_type_set_collection_by_name_n`
- [x] `cass_user_type_set_tuple`
- [x] `cass_user_type_set_tuple_by_name`
- [x] `cass_user_type_set_tuple_by_name_n`
- [x] `cass_user_type_set_user_type`
- [x] `cass_user_type_set_user_type_by_name`
- [x] `cass_user_type_set_user_type_by_name_n`

**Comment by muzarski** [comment]
We are not planning to support custom types. Closing this one, since remaining API functions are implemented.
