### ISSUE TITLE
CassCollection missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#52]
Function list:

- [x] `cass_collection_new_from_data_type`
- [x] `cass_collection_data_type`
- [ ] `cass_collection_append_custom`
- [ ] `cass_collection_append_custom_n`
- [x] `cass_collection_append_uuid`
- [x] `cass_collection_append_inet`
- [x] `cass_collection_append_decimal`
- [x] `cass_collection_append_duration`
- [x] `cass_collection_append_collection`
- [x] `cass_collection_append_tuple`
- [x] `cass_collection_append_user_type`

**Comment by muzarski** [comment]
We are not planning to support custom types. Closing this one, since remaining API functions are implemented.
