### ISSUE TITLE
CassStatement missing functions

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/cpp-rs-driver#53]
Function list:

- [ ] `cass_statement_bind_custom`
- [ ] `cass_statement_bind_custom_n`
- [ ] `cass_statement_bind_custom_by_name`
- [ ] `cass_statement_bind_custom_by_name_n`
- [ ] `cass_statement_bind_decimal`
- [ ] `cass_statement_bind_decimal_by_name`
- [ ] `cass_statement_bind_decimal_by_name_n`
- [ ] `cass_statement_bind_duration`
- [ ] `cass_statement_bind_duration_by_name`
- [ ] `cass_statement_bind_duration_by_name_n`
- [x] `cass_statement_bind_user_type_by_name`
- [x] `cass_statement_bind_user_type_by_name_n`

**Comment by roydahan** [comment]
Closing in favor of dedicated issues per topic.

**Comment by dkropachev** [comment]
@Lorak-mmk, @wprzytula  it looks like we did not create issues for these functions
